name: "Android"

on:
  workflow_call:
    inputs:
      build-id:
        description: 'Identifier for workflows and caching'
        type: string
        required: true
      cpm-cache-version:
        description: "CPM Cache Version"
        type: string
        required: true
      devel:
        description: 'Development mode (disables update checker)'
        type: string
        required: true

env:
  ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}

jobs:
  and-matrix:
    name: "Generate Android targets"
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - id: set
        run: ./.ci/matrix/android.sh

  android:
    name: "Android"
    needs: [and-matrix]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.and-matrix.outputs.targets) }}
    env:
      TARGET: "${{ matrix.target.flavor }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-amd64-universal
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: ./.ci/android/deps.sh

      - name: Build
        run: JAVA_HOME=$JAVA_HOME_17_X64 ./.ci/android/build.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: android-${{ matrix.target.flavor }}
          archive: false
          path: artifacts/*.apk
