name: "AppImage"

on:
  workflow_call:
    inputs:
      build-id:
        description: "Identifier for workflows and caching"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM Cache Version"
        type: string
        required: true
      devel:
        description: "Development mode (disables update checker)"
        type: string
        required: true
      force_pgo:
        description: "Force PGO builds"
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}
  FORCE_PGO: ${{ inputs.force_pgo }}

jobs:
  # TODO(crueter): All matrix steps can be combined into one, probably.
  set-matrix:
    name: "Generate AppImage Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
      compiler: ${{ steps.set.outputs.compiler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - id: set
        run: ./.ci/matrix/appimage.sh

  linux:
    name: "AppImage ${{ matrix.os.arch }} ${{ matrix.compiler.program }} ${{ matrix.compiler.target }}"
    needs: [set-matrix]
    runs-on: ${{ matrix.os.runs-on }}
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
      options: --privileged --device /dev/fuse

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
        compiler: ${{ fromJson(needs.set-matrix.outputs.compiler) }}

    env:
      TARGET: "${{ matrix.os.arch }}"
      COMPILER: "${{ matrix.compiler.program }}"
      PGO_TARGET: "${{ matrix.compiler.target }}"
      FULL_ARCH: ${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler.program }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: ./.ci/linux/deps.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Configure
        run: ./.ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        run: cmake --build build -- -d explain -d stats --verbose

      - name: Package
        run: ./.ci/linux/package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload AppImage
        uses: actions/upload-artifact@v7
        with:
          name: linux-${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}
          path: ./artifacts/*.AppImage
          archive: false

      - name: Upload zsync
        uses: actions/upload-artifact@v7
        if: ${{ inputs.devel != 'true' }}
        with:
          name: linux-${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}-zsync
          path: ./artifacts/*.AppImage.zsync
          archive: false
