name: "macOS"

on:
  workflow_call:
    inputs:
      build-id:
        description: 'Identifier for workflows and caching'
        type: string
        required: true
      cpm-cache-version:
        description: 'CPM Cache Version'
        type: string
        required: true
      devel:
        description: 'Development mode (disables update checker)'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}

jobs:
  macos:
    name: "macOS (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: macos-latest
            arch: arm64
        compiler: [clang]

    env:
      TARGET: m1
      COMPILER: clang

      # TODO: force_pgo input, matrix, etc.
      PGO_TARGET: standard

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: ./.ci/macos/deps.sh

      - name: Configure
        run: ./.ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        run: cmake --build build

      - name: Package
        run: ./.ci/macos/dmg.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos
          archive: false
          path: artifacts/*
